on: push
jobs:
  init:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

  install-dependencies:
    runs-on: self-hosted
    needs: init
    steps:
      - name: Install dependencies
        run: pnpm install

  lint:
    runs-on: self-hosted
    needs: install-dependencies
    steps:
      - name: Check lint
        run: pnpm lint

  coverage:
    runs-on: self-hosted
    needs: install-dependencies
    steps:
      - name: Test coverage
        run: pnpm coverage

  build:
    needs: install-dependencies
    runs-on: self-hosted
    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build Android
        run: |
          cd android
          ./gradlew build
